name: 'yaon'
description: 'A simple library to parse either a string from either yaml or json.'
homepage: 'https://github.com/peiffer-innovations/yaon'
version: '1.1.1'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  logging: '^1.1.1'
  yaml: '^3.1.2'

dev_dependencies:
  bson: '^4.0.0'
  test: '^1.24.2'
  yaml_writer: '^1.0.3'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
