name: 'yaon'
description: 'A simple library to parse either a string from either yaml or json.'
homepage: 'https://github.com/peiffer-innovations/yaon'
version: '1.1.4+5'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  logging: '^1.2.0'
  yaml: '^3.1.2'

dev_dependencies: 
  bson: '^5.0.4'
  flutter_lints: '^3.0.1'
  test: '^1.25.2'
  yaml_writer: '^2.0.0'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'uuid'
  - 'vector_math'
  - 'webdriver'
